/**
  ******************************************************************************
  * @file    cmox_kdf.h
  * @brief   Header file for the KDF module
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef CMOX_KDF_H
#define CMOX_KDF_H

#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */

/* Include files -------------------------------------------------------------*/
#include <stdint.h>
#include <stddef.h>
#include "cmox_kdf_retvals.h"

/** @addtogroup CMOX_KDF
  * @{
  */

/* Macros --------------------------------------------------------------------*/
/* Public types --------------------------------------------------------------*/

/** @defgroup CMOX_KDF_PUBLIC_TYPES KDF module public types
  * @{
  */

/**
  * @brief KDF Virtual Table
  *
  * This type specifies a pointer to the virtual table containing the methods
  * for a particular algorithm (e.g. HKDF)
  */
typedef const struct cmox_kdf_vtableStruct_st *cmox_kdf_vtable_t;

/**
  * @brief KDF algorithm type
  *
  * This type specifies the algorithm to use with the kdf module (e.g. HKDF).
  * The type is defined as a pointer to a structure, that
  * contains the functions for the specific algorithm, defined in the library
  * internally
  */
typedef const struct cmox_kdf_algoStruct_st *cmox_kdf_algo_t;


/**
  * @brief KDF handle structure definition
  */
typedef struct
{
  cmox_kdf_vtable_t table;  /*!< KDF virtual table */
  uint32_t internalState;   /*!< KDF internal state */
} cmox_kdf_handle_t;

/**
  * @}
  */

/* Public constants ----------------------------------------------------------*/
/* Public methods prototypes -------------------------------------------------*/

/** @defgroup CMOX_KDF_PUBLIC_METHODS KDF public method prototypes
  * @{
  */

/**
  * @brief Cleanup the kdf handler
  *
  * @param P_pThis KDF handler to cleanup
  * @return cmox_kdf_retval_t KDF return value
  */
cmox_kdf_retval_t cmox_kdf_cleanup(cmox_kdf_handle_t *P_pThis);

/**
  * @brief Initialize the kdf handle based on the selected algorithm
  *
  * @param P_pThis KDF handle to initialize
  * @return cmox_kdf_retval_t KDF return value
  * @note The kdf handle must be derived from an algorithm-specific handle
  *       using the correct construct
  */
cmox_kdf_retval_t cmox_kdf_init(cmox_kdf_handle_t *P_pThis);

/**
  * @brief Set the input key
  *
  * @param P_pThis KDF handle to set
  * @param P_pInputKey Buffer of bytes containing the input key
  * @param P_inputKeyLen Size in bytes of the input key
  * @return cmox_kdf_retval_t KDF return value
  */
cmox_kdf_retval_t cmox_kdf_setInputKey(cmox_kdf_handle_t *P_pThis,
                                       const uint8_t *P_pInputKey,
                                       size_t P_inputKeyLen);

/**
  * @brief Set the info
  *
  * @param P_pThis KDF handle to set
  * @param P_pInfo Buffer of bytes containing the info
  * @param P_infoLen Size in bytes of the info
  * @return cmox_kdf_retval_t KDF return value
  */
cmox_kdf_retval_t cmox_kdf_setInfo(cmox_kdf_handle_t *P_pThis,
                                   const uint8_t *P_pInfo,
                                   size_t P_infoLen);

/**
  * @brief Set the salt
  *
  * @param P_pThis KDF handle to set
  * @param P_pSalt Buffer of bytes containing the salt
  * @param P_saltLen Size in bytes of the salt
  * @return cmox_kdf_retval_t KDF return value
  */
cmox_kdf_retval_t cmox_kdf_setSalt(cmox_kdf_handle_t *P_pThis,
                                   const uint8_t *P_pSalt,
                                   size_t P_saltLen);

/**
  * @brief Generate output key material (can be called multiple times)
  *
  * @param P_pThis KDF handle used for appending the data to kdf
  * @param P_pOutput Buffer of bytes where the digest will be stored
  * @param P_expectedOutputLen Size in bytes of the desired output
  * @param P_pComputedOutputLen Number of bytes generated by the function.
  *        It is an optional parameter and can be set to NULL if not needed.
  * @return cmox_kdf_retval_t KDF return value
  */
cmox_kdf_retval_t cmox_kdf_generateOutput(cmox_kdf_handle_t *P_pThis,
                                          uint8_t *P_pOutput,
                                          size_t P_expectedOutputLen,
                                          size_t *P_pComputedOutputLen);

/**
  * @brief Compute the digest of a message using a kdf algorithm
  *
  * @param P_algo Identifier of the kdf algorithm to use for the computation.
  *               This parameter can be one of the following:
  *               @arg CMOX_HKDF_SHA512_ALGO
  * @param P_pInputKey Buffer of bytes containing the input key
  * @param P_inputKeyLen Size in bytes of the input key
  * @param P_pSalt Buffer of bytes containing the salt
  * @param P_saltLen Size in bytes of the info
  * @param P_pInfo Buffer of bytes containing the info
  * @param P_infoLen Size in bytes of the info
  * @param P_pOutput Buffer of bytes that will contain the computed output
  * @param P_expectedOutputLen Size in bytes of the desired output
  * @param P_pComputedOutputLen Number of bytes generated by the function.
  *        It is an optional parameter and can be set to NULL if not needed.
  * @return cmox_kdf_retval_t
  */
cmox_kdf_retval_t cmox_kdf_compute(cmox_kdf_algo_t P_algo,
                                   const uint8_t *P_pInputKey,
                                   size_t P_inputKeyLen,
                                   const uint8_t *P_pSalt,
                                   size_t P_saltLen,
                                   const uint8_t *P_pInfo,
                                   size_t P_infoLen,
                                   uint8_t *P_pOutput,
                                   const size_t P_expectedOutputLen,
                                   size_t *P_pComputedOutputLen);

/**
  * @}
  */

/**
  * @}
  */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CMOX_KDF_H */

