/**
  ******************************************************************************
  * @file    se_crypto_bootloader.c
  * @author  MCD Application Team
  * @brief   Secure Engine CRYPTO module used by the bootloader.
  *
  *          STM32F072 port: crypto backend is the ST X-CUBE-CRYPTOLIB V5
  *          (CMOX) Cortex-M0/M0+ software library
  *          (Middlewares/ST/STM32_Cryptographic/lib/libSTM32Cryptographic_CM0_CM0PLUS.a):
  *            - SHA-256 : cmox_sha256_* incremental hashing
  *            - ECDSA P-256 verify : cmox_ecdsa_verify (SECP256R1)
  *
  *          Supported scheme: SECBOOT_ECCDSA_WITH_AES128_CBC_SHA256 with the
  *          NO_LOADER / direct-flash flow: the active slot holds the firmware
  *          in CLEAR, boot-time verification is ECDSA over the header + SHA-256
  *          over the body. The AES-CBC decrypt/encrypt services only exist for
  *          the unused download-slot install path and deliberately return
  *          SE_ERROR.
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2017 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file in
  * the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include <string.h>
#include "se_crypto_bootloader.h"
#include "se_low_level.h"         /* required for assert_param */
#include "se_key.h"               /* SE_ReadKey_1_Pub() generated from the product public key */
#include "cmox_crypto.h"          /* CMOX: SHA-256 + ECDSA P-256 verify */

#if (SECBOOT_CRYPTO_SCHEME != SECBOOT_ECCDSA_WITH_AES128_CBC_SHA256)
#error "The STM32F072 port only supports SECBOOT_ECCDSA_WITH_AES128_CBC_SHA256 (clear direct-flash flow)."
#endif /* SECBOOT_CRYPTO_SCHEME */

/** @addtogroup SE Secure Engine
  * @{
  */

/** @addtogroup SE_CORE SE Core
  * @{
  */

/** @defgroup  SE_CRYPTO SE Crypto
  * @brief Crypto services (used by the bootloader and the SE callgate)
  * @{
  */

/* Private defines -----------------------------------------------------------*/
/* ST example value for a P-256 ECDSA verify working buffer. Trim with
 * cmox_membuf_getMaxUsed() only after measuring on-target. */
#define SE_ECC_WORKING_BUFFER_SIZE   2000U

/* Private variables ---------------------------------------------------------*/
/* These statics live in the dedicated SE RAM region (.se_bss) — see the linker
 * script — and are wiped by SFU_SE_RAM_Erase() before leaving the bootloader
 * (app launch or DFU entry). The SE RAM region is sized (4K) to hold them. */
static cmox_sha256_handle_t m_Sha256Ctx;                      /*!< FwTag digest context */
static uint8_t              m_aSE_PubKey[SE_ASYM_PUBKEY_LEN]; /*!< ECDSA public key scratch */
static uint8_t              m_EccWorkingBuffer[SE_ECC_WORKING_BUFFER_SIZE]; /*!< CMOX ECC membuf */

/* Handle returned by cmox_sha256_construct(); points into m_Sha256Ctx. */
static cmox_hash_handle_t  *m_pSha256;

/* Private functions ---------------------------------------------------------*/

/**
  * @brief Retrieve the ECDSA public key for signature verification.
  *        Single active image configuration: always key #1 (see se_key.s,
  *        generated by py-tools/gen_se_key_s.py from the product key pair).
  * @param pxSE_Metadata metadata of the image to authenticate (unused, single key)
  * @param paSE_PubKey destination buffer (SE_ASYM_PUBKEY_LEN = 64 bytes, raw X||Y)
  * @retval void
  */
static void SE_CRYPTO_ReadKey_Pub(SE_FwRawHeaderTypeDef *pxSE_Metadata, uint8_t *paSE_PubKey)
{
  (void)pxSE_Metadata;
  SE_ReadKey_1_Pub(paSE_PubKey);
}

/* Exported functions --------------------------------------------------------*/

/**
  * @brief Secure Engine Encrypt Init function.
  *        Not used in the direct-flash (NO_LOADER) configuration.
  */
SE_ErrorStatus SE_CRYPTO_Encrypt_Init(SE_FwRawHeaderTypeDef *pxSE_Metadata, uint32_t SE_FwType)
{
  (void)pxSE_Metadata;
  (void)SE_FwType;
  return SE_ERROR;
}

/**
  * @brief Secure Engine Header Append function. Nothing to do for the
  *        ECDSA/SHA-256 scheme.
  */
SE_ErrorStatus SE_CRYPTO_Header_Append(const uint8_t *pInputBuffer, int32_t InputSize)
{
  (void)pInputBuffer;
  (void)InputSize;
  return SE_SUCCESS;
}

/**
  * @brief Secure Engine Encrypt Append function — unused, see Encrypt_Init.
  */
SE_ErrorStatus SE_CRYPTO_Encrypt_Append(const uint8_t *pInputBuffer, int32_t InputSize, uint8_t *pOutputBuffer,
                                        int32_t *pOutputSize)
{
  (void)pInputBuffer;
  (void)InputSize;
  (void)pOutputBuffer;
  (void)pOutputSize;
  return SE_ERROR;
}

/**
  * @brief Secure Engine Encrypt Finish function — unused, see Encrypt_Init.
  */
SE_ErrorStatus SE_CRYPTO_Encrypt_Finish(uint8_t *pOutputBuffer, int32_t *pOutputSize)
{
  (void)pOutputBuffer;
  (void)pOutputSize;
  return SE_ERROR;
}

/**
  * @brief Secure Engine Decrypt Init function.
  *        The AES-CBC decrypt path belongs to the download-slot install flow,
  *        which this direct-flash bootloader does not use (USB DFU writes the
  *        clear signed image straight into the active slot).
  */
SE_ErrorStatus SE_CRYPTO_Decrypt_Init(SE_FwRawHeaderTypeDef *pxSE_Metadata, uint32_t SE_FwType)
{
  (void)pxSE_Metadata;
  (void)SE_FwType;
  return SE_ERROR;
}

/**
  * @brief Secure Engine Decrypt Append function — unused, see Decrypt_Init.
  */
SE_ErrorStatus SE_CRYPTO_Decrypt_Append(const uint8_t *pInputBuffer, int32_t InputSize, uint8_t *pOutputBuffer,
                                        int32_t *pOutputSize)
{
  (void)pInputBuffer;
  (void)InputSize;
  (void)pOutputBuffer;
  (void)pOutputSize;
  return SE_ERROR;
}

/**
  * @brief Secure Engine Decrypt Finish function — unused, see Decrypt_Init.
  */
SE_ErrorStatus SE_CRYPTO_Decrypt_Finish(uint8_t *pOutputBuffer, int32_t *pOutputSize)
{
  (void)pOutputBuffer;
  (void)pOutputSize;
  return SE_ERROR;
}

/**
  * @brief Secure Engine Firmware Authentication Init function.
  *        The firmware tag (FwTag) is a SHA-256 digest of the clear firmware.
  * @param pxSE_Metadata Metadata (unused for a hash).
  * @param SE_FwType: Type of Fw Image (unused).
  * @retval SE_ErrorStatus SE_SUCCESS if successful, SE_ERROR otherwise.
  */
SE_ErrorStatus SE_CRYPTO_AuthenticateFW_Init(SE_FwRawHeaderTypeDef *pxSE_Metadata, uint32_t SE_FwType)
{
  (void)pxSE_Metadata;
  (void)SE_FwType;

  m_pSha256 = cmox_sha256_construct(&m_Sha256Ctx);
  if (m_pSha256 == NULL)
  {
    return SE_ERROR;
  }
  if (cmox_hash_init(m_pSha256) != CMOX_HASH_SUCCESS)
  {
    return SE_ERROR;
  }
  if (cmox_hash_setTagLen(m_pSha256, CMOX_SHA256_SIZE) != CMOX_HASH_SUCCESS)
  {
    return SE_ERROR;
  }
  return SE_SUCCESS;
}

/**
  * @brief Secure Engine Firmware Authentication Append function.
  * @param pInputBuffer: pointer to Input Buffer.
  * @param InputSize: Input Size (bytes).
  * @param pOutputBuffer: unused for a hash (kept for API compatibility).
  * @param pOutputSize: unused for a hash (kept for API compatibility).
  * @retval SE_ErrorStatus SE_SUCCESS if successful, SE_ERROR otherwise.
  */
SE_ErrorStatus SE_CRYPTO_AuthenticateFW_Append(const uint8_t *pInputBuffer, int32_t InputSize, uint8_t *pOutputBuffer,
                                               int32_t *pOutputSize)
{
  (void)pOutputBuffer;

  if ((pInputBuffer == NULL) || (InputSize < 0) || (m_pSha256 == NULL))
  {
    return SE_ERROR;
  }

  if (cmox_hash_append(m_pSha256, pInputBuffer, (size_t)InputSize) != CMOX_HASH_SUCCESS)
  {
    return SE_ERROR;
  }

  if (pOutputSize != NULL)
  {
    *pOutputSize = InputSize;
  }
  return SE_SUCCESS;
}

/**
  * @brief Secure Engine Firmware Authentication Finish function.
  * @param pOutputBuffer: pointer to Output Buffer (receives the SHA-256 digest).
  * @param pOutputSize: pointer to Output Size (bytes): 32.
  * @retval SE_ErrorStatus SE_SUCCESS if successful, SE_ERROR otherwise.
  */
SE_ErrorStatus SE_CRYPTO_AuthenticateFW_Finish(uint8_t *pOutputBuffer, int32_t *pOutputSize)
{
  size_t computed = 0U;

  if ((pOutputBuffer == NULL) || (pOutputSize == NULL) || (m_pSha256 == NULL))
  {
    return SE_ERROR;
  }

  if (cmox_hash_generateTag(m_pSha256, pOutputBuffer, &computed) != CMOX_HASH_SUCCESS)
  {
    (void)cmox_hash_cleanup(m_pSha256);
    m_pSha256 = NULL;
    return SE_ERROR;
  }
  (void)cmox_hash_cleanup(m_pSha256);
  m_pSha256 = NULL;

  if (computed != CMOX_SHA256_SIZE)
  {
    return SE_ERROR;
  }

  *pOutputSize = (int32_t)computed;
  return SE_SUCCESS;
}

/**
  * @brief Secure Engine header authentication function.
  *        Verifies the ECDSA P-256 signature (raw R||S) of the authenticated
  *        part of the firmware header against the embedded product public key,
  *        with a fault-injection double check (both return value and the
  *        fault_check out-param must equal CMOX_ECC_AUTH_SUCCESS).
  * @param pxSE_Metadata: pointer to the firmware header.
  * @retval SE_ErrorStatus SE_SUCCESS if successful, SE_ERROR otherwise.
  */
SE_ErrorStatus SE_CRYPTO_Authenticate_Metadata(SE_FwRawHeaderTypeDef *pxSE_Metadata)
{
  SE_ErrorStatus e_ret_status = SE_ERROR;
  cmox_ecc_handle_t ecc_ctx;
  cmox_ecc_retval_t retval;
  cmox_hash_retval_t hretval;
  uint32_t fault_check = CMOX_ECC_AUTH_FAIL;
  uint8_t digest[CMOX_SHA256_SIZE];
  size_t computed = 0U;

  if (pxSE_Metadata == NULL)
  {
    return SE_ERROR;
  }

  /* Retrieve the public key (raw X||Y, 64 bytes) from the protected key
   * functions generated from the product public key. */
  SE_CRYPTO_ReadKey_Pub(pxSE_Metadata, &(m_aSE_PubKey[0]));

  /* SHA-256 of the authenticated header region (everything before the
   * signature), one-shot. */
  hretval = cmox_hash_compute(CMOX_SHA256_ALGO,
                              (const uint8_t *)pxSE_Metadata, (size_t)SE_FW_AUTH_LEN,
                              digest, CMOX_SHA256_SIZE, &computed);
  if ((hretval != CMOX_HASH_SUCCESS) || (computed != CMOX_SHA256_SIZE))
  {
    (void)memset(digest, 0, sizeof(digest));
    return SE_ERROR;
  }

  /* ECDSA P-256 verification. Verify-only, low-memory curve variant + the
   * small math implementation to keep the CM0 footprint down. */
  cmox_ecc_construct(&ecc_ctx, CMOX_MATH_FUNCS_SMALL, m_EccWorkingBuffer, sizeof(m_EccWorkingBuffer));

  retval = cmox_ecdsa_verify(&ecc_ctx,
                             CMOX_ECC_SECP256R1_LOWMEM_VERIFY,
                             m_aSE_PubKey, SE_ASYM_PUBKEY_LEN,
                             digest, CMOX_SHA256_SIZE,
                             pxSE_Metadata->HeaderSignature, SE_HEADER_SIGN_LEN,
                             &fault_check);

  cmox_ecc_cleanup(&ecc_ctx);

  /* Accept ONLY if both the return value and the fault-check out-param report
   * success (anti fault-injection). Compare against SUCCESS, never FAIL. */
  if ((retval == CMOX_ECC_AUTH_SUCCESS) && (fault_check == CMOX_ECC_AUTH_SUCCESS))
  {
    e_ret_status = SE_SUCCESS;
  }

  /* Cleanup the digest scratch (defense in depth; the pub key is not secret) */
  (void)memset(digest, 0, sizeof(digest));

  return e_ret_status;
}

/**
  * @brief Lock the CKS keys (STM32WB Customer Key Storage service).
  *        Not applicable on STM32F072 — nothing to do.
  * @retval void
  */
void SE_CRYPTO_Lock_CKS_Keys(void)
{
  ;
}

/**
  * @}
  */

/**
  * @}
  */

/**
  * @}
  */
