#!/usr/bin/env python3
"""
gen_se_key_s.py  —  Generate SECoreBin/Startup/se_key.s from key material.

The se_key.s assembly file embeds two secrets in the SE Key flash region:
  - SE_ReadKey_1      : 16-byte AES-128 symmetric key (used for FW encryption)
  - SE_ReadKey_1_Pub  : 64-byte ECC P-256 public key  (used for signature verify)

Two instruction encodings are supported:

  cortex-m7 (also any ARMv7-M: M3/M4/M7):
    Key bytes are materialized with MOVW (lower 16 bits) / MOVT (upper 16
    bits) into R1-R4, then stored with a no-writeback STM. Keeps the key
    purely in code (PCROP / execute-only friendly).

  cortex-m0 (ARMv6-M / Thumb-1, e.g. STM32F072):
    MOVW/MOVT and no-writeback STM do not exist. Words are loaded from the
    literal pool (LDR Rn, =imm32) and stored with STM R0! (writeback form).
    The literals land in the same .SE_Key_Data section right after the code
    (the F0 has no PCROP anyway; the section is fixed at a known address by
    the linker script for a future WRP/RDP pass).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Encoding helpers
# ---------------------------------------------------------------------------

def _bytes_to_movw_movt_block(data16: bytes) -> list[str]:
    """Return MOVW/MOVT/STM assembly lines for a 16-byte block into R1-R4 (ARMv7-M)."""
    assert len(data16) == 16, f"Expected 16 bytes, got {len(data16)}"
    lines: list[str] = []
    for i in range(4):
        word = int.from_bytes(data16[i * 4 : i * 4 + 4], "little")
        lo = word & 0xFFFF
        hi = (word >> 16) & 0xFFFF
        reg = f"R{i + 1}"
        lines.append(f"\tMOVW {reg}, #0x{lo:04x}")
        lines.append(f"\tMOVT {reg}, #0x{hi:04x}")
    lines.append("\tSTM R0, {R1-R4}")
    return lines


def _bytes_to_ldr_literal_block(data16: bytes) -> list[str]:
    """Return LDR-literal/STM-writeback assembly lines for a 16-byte block (ARMv6-M).

    STM R0! advances R0 by 16 automatically, so no ADD between blocks is
    needed at the call site.
    """
    assert len(data16) == 16, f"Expected 16 bytes, got {len(data16)}"
    lines: list[str] = []
    for i in range(4):
        word = int.from_bytes(data16[i * 4 : i * 4 + 4], "little")
        reg = f"R{i + 1}"
        lines.append(f"\tLDR {reg}, =0x{word:08x}")
    lines.append("\tSTM R0!, {R1-R4}")
    return lines


def generate_se_key_s(aes_key: bytes, pub_key_x: bytes, pub_key_y: bytes,
                      cpu: str = "cortex-m7") -> str:
    """
    Build the full se_key.s text.

    Parameters
    ----------
    aes_key   : 16 bytes — AES-128 symmetric key (raw)
    pub_key_x : 32 bytes — P-256 public key X coordinate (big-endian)
    pub_key_y : 32 bytes — P-256 public key Y coordinate (big-endian)
    cpu       : "cortex-m7" (ARMv7-M encoding) or "cortex-m0" (Thumb-1 encoding)

    Returns
    -------
    str — contents of se_key.s
    """
    if len(aes_key) != 16:
        raise ValueError(f"AES key must be 16 bytes, got {len(aes_key)}")
    if len(pub_key_x) != 32:
        raise ValueError(f"pub_key_x must be 32 bytes, got {len(pub_key_x)}")
    if len(pub_key_y) != 32:
        raise ValueError(f"pub_key_y must be 32 bytes, got {len(pub_key_y)}")
    if cpu not in ("cortex-m7", "cortex-m0"):
        raise ValueError(f"Unsupported cpu: {cpu}")

    thumb1 = (cpu == "cortex-m0")
    block = _bytes_to_ldr_literal_block if thumb1 else _bytes_to_movw_movt_block

    pub_key = pub_key_x + pub_key_y  # 64 bytes total

    lines: list[str] = []
    lines += [
        "/**",
        "  ******************************************************************************",
        "  * @file      se_key.s",
        f"  * @brief     ReadKey functions ({cpu}) - generated by gen_se_key_s.py",
        "  *            DO NOT EDIT MANUALLY.  Re-run generate_keys.py to refresh.",
        "  ******************************************************************************",
        "  */",
        "",
        "\t.section .SE_Key_Data,\"ax\",%progbits",
        "\t.syntax unified",
        f"\t.cpu {cpu}",
        "\t.thumb",
        "\t.global SE_ReadKey_1",
    ]

    # -----------------------------------------------------------------------
    # SE_ReadKey_1 — AES-128 symmetric key (16 bytes)
    # -----------------------------------------------------------------------
    lines.append("\t.thumb_func")   # mark as a Thumb function (required for BL relocs)
    lines.append("SE_ReadKey_1:")
    lines.append("\tPUSH {R1-R5}")
    if thumb1:
        lines.append("\tMOV R5, R0")    # preserve caller's buffer pointer (STM! clobbers R0)
    lines += block(aes_key)
    if thumb1:
        lines.append("\tMOV R0, R5")
    lines += [
        "\tPOP {R1-R5}",
        "\tBX LR",
    ]
    if thumb1:
        lines.append("\t.ltorg")        # literal pool for the AES key words
    lines.append("")

    # -----------------------------------------------------------------------
    # SE_ReadKey_1_Pub — ECC P-256 public key (64 bytes in 4 x 16-byte blocks)
    # -----------------------------------------------------------------------
    lines.append("\t.global SE_ReadKey_1_Pub")
    lines.append("\t.thumb_func")   # mark as a Thumb function (required for BL relocs)
    lines.append("SE_ReadKey_1_Pub:")
    lines.append("\tPUSH {R1-R5}")
    if thumb1:
        lines.append("\tMOV R5, R0")

    for block_idx in range(4):
        chunk = pub_key[block_idx * 16 : block_idx * 16 + 16]
        lines += block(chunk)
        if (not thumb1) and block_idx < 3:
            lines.append("\tADD R0, R0, #16")

    if thumb1:
        lines.append("\tMOV R0, R5")
    lines += [
        "\tPOP {R1-R5}",
        "\tBX LR",
    ]
    if thumb1:
        lines.append("\t.ltorg")        # literal pool for the public-key words
    lines += [
        "",
        "\t.end",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate se_key.s from AES and ECC key files."
    )
    parser.add_argument(
        "--aes-key", required=True,
        help="Path to the 16-byte raw AES-128 key file (binary).",
    )
    parser.add_argument(
        "--pub-key-x", required=True,
        help="Path to the 32-byte raw P-256 X coordinate (big-endian binary).",
    )
    parser.add_argument(
        "--pub-key-y", required=True,
        help="Path to the 32-byte raw P-256 Y coordinate (big-endian binary).",
    )
    parser.add_argument(
        "--cpu", default="cortex-m0", choices=["cortex-m0", "cortex-m7"],
        help="Target CPU instruction set (default: cortex-m0 for the STM32F072).",
    )
    parser.add_argument(
        "--output",
        default=str(
            Path(__file__).resolve().parent.parent
            / "SECoreBin" / "Startup" / "se_key.s"
        ),
        help="Output path for se_key.s (default: SECoreBin/Startup/se_key.s).",
    )
    args = parser.parse_args()

    aes_key  = Path(args.aes_key).read_bytes()
    pub_x    = Path(args.pub_key_x).read_bytes()
    pub_y    = Path(args.pub_key_y).read_bytes()

    content = generate_se_key_s(aes_key, pub_x, pub_y, cpu=args.cpu)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="ascii")

    print(f"[gen_se_key_s] Written: {out_path} ({args.cpu})")


if __name__ == "__main__":
    main()
